### ISSUE TITLE
Is the volume expansion fully supported?

### ISSUE THREAD

**Issue by bkalcho** [datainfrahq/druid-operator#116]
To be specific, I was reading your support for volume expansion: https://github.com/datainfrahq/druid-operator/blob/v1.1.1/docs/features.md#volume-expansion-of-druid-nodes-running-as-statefulsets

I have enabled `scalePvcSts` and using gp3 storage class, that has enabled `allowVolumeExpansion`.
When I change the size of the volume from let say 30G to 100G, I see following errors in the druid-operator logs:
```
2023-10-26T11:53:54Z    DEBUG   events  Failed to update [...:*v1.StatefulSet] due to [StatefulSet.apps "..." is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden].     {"type": "Warning", "object": {"kind":"Druid","namespace":"...","name":"cluster","uid":"...","apiVersion":"druid.apache.org/v1alpha1","resourceVersion":"..."}, "reason": "DruidOperatorUpdateFail"}
```
I do not see Druid performs this:
- Druid Operator behind the scenes performs seamless update of the statefulset, plus patch the pvc's with desired size defined in the druid CR.
- Druid operator shall perform a cascade deletion of the sts, and shall patch the pvc. Cascade deletion has no affect to the pods running, queries are served and no downtime is experienced

To be honest, it does not perform seamless update of the statefulset, while VolumeClaimTemplate changed storage request.

Using druid version tagged with v1.1.1, and running k8s 1.23 in EKS

**Comment by bkalcho** [comment]
OK, I had Druid run some time, then I have added this `scalePvcSts` flag. gp3 `allowVolumeExpansion` was already enabled (I think this is the default for gp3).
I verified all these settings are active:
```
kubectl get storageclass gp3 -o yaml
kubectl get druid -o yaml
```
After that I have updated just `volumeClaimTemplate` to be specific just storage request, from 30Gi to 50Gi. This was just for the testing purpose, so I was very cautious not to change anything else. I made a change in the Druid CR manifest and submitted it to k8s.
I verified it is present by doing:
```kubectl get druid -n druid-operator -o yaml```
It is present there, but nothing happened regarding sts nor the pvc. Still the same initial size of 30Gi for the PV,PVC and sts has not been changed.

**Comment by AdheipSingh** [comment]
i ll get back to you on this. Personally haven't faced this issue ( i also haven't scaled clusters for a long time :) ). 
Will debug this.

**Comment by AdheipSingh** [comment]
<img width="962" alt="Screenshot 2023-11-08 at 12 51 14 PM" src="https://github.com/datainfrahq/druid-operator/assets/34169002/4893d6e2-e734-4626-966a-ce0a19909db7">

@bkalcho It seems to be working fine. I have checked this on eks. 

```
I do not see Druid performs this:

Druid Operator behind the scenes performs seamless update of the statefulset, plus patch the pvc's with desired size defined in the druid CR.
Druid operator shall perform a cascade deletion of the sts, and shall patch the pvc. Cascade deletion has no affect to the pods running, queries are served and no downtime is experienced
To be honest, it does not perform seamless update of the statefulset, while VolumeClaimTemplate changed storage request.
```
Please provide sufficient evidence to support this claim. 

Please note :
- To perform this operator expects all pods to be in ready state.
- Even if one sts is 0/1 the operator will not perform this action.

**Comment by bkalcho** [comment]
Thank you very much for your testing. I am experiencing reconciliation errors, caused by the migration from the Operator Framework to Kubebuilder, that halt the Controller reconciliation loop, so it appears this might be the blocking cause.

**Comment by AdheipSingh** [comment]
feel free to re-open. thanks closing for now
