### ISSUE TITLE
Where to mount PVC in Druid

### ISSUE THREAD

**Issue by tapojit047** [datainfrahq/druid-operator#117]
- I was deploying Druid using the operator. After deployment, I can see that the `druid-operator` does not actually provide any `PVC` configuration by default. Rather there are fields like  `volumeClaimTemplates`, `volumeMounts` and `volumes`, in the druid YAML. So, my guess is, I need to mount my own `pvcs` in the necessary nodes.

- After exploring, I think I need `PVC` in `Historicals` and `MiddleManagers` nodes aka `Data Nodes`. And the path should be, for Historicals, `/druid/data/segments` and for MiddleManagers, `/druid/data/baseTaskDir`.
 
- I want to know is that correct or not, if not, in which nodes and paths, the volumes should be mounted.

**Comment by AdheipSingh** [comment]
- volumeClaimTemplates is sufficient to mount PVC's for statefulsets ie MM and Historicals. If you need to mount PVC for other deployments ( IMHO which not needed ) you can create pvc's. Operator does support it. https://github.com/datainfrahq/druid-operator/blob/master/controllers/druid/handler.go#L268C15-L268C36

- use sts for historicals and MM. Rest are stateless deployments are sufficient.

**Comment by AdheipSingh** [comment]
feel free to re-open, or check in on slack. 
thanks
