### ISSUE TITLE
druid:28.0.0 Support

### ISSUE THREAD

**Issue by buffaloDeveloper** [datainfrahq/druid-operator#126]
Is there anyway to use apache/druid:28.0.0?  I need to use some of the newer features.

**Comment by buffaloDeveloper** [comment]
I tried what you said and the operator performed the upgrade, but I am seeing errors now in the Druid console: 
<img width="1806" alt="image" src="https://github.com/datainfrahq/druid-operator/assets/3186418/5029c3a0-bf18-45ce-9986-1dec13c3fece">

**Comment by AdheipSingh** [comment]
@buffaloDeveloper pls check pod logs.

**Comment by buffaloDeveloper** [comment]
Tried a clean install.  Same error in the console.  I don't see any errors in the pod logs though.
`Unknown exception / Compiling "GeneratedMetadata_CollationHandler" in Line 19, Column 14: Line 31, Column 50: Compiling "collations(org.apache.calcite.rel.RelNode r, org.apache.calcite.rel.metadata.RelMetadataQuery mq)" / org.codehaus.commons.compiler.InternalCompilerException`
