### ISSUE TITLE
Upgrading from old druid.io's cluster-druid-operator to this repo

### ISSUE THREAD

**Issue by winsmith** [datainfrahq/druid-operator#127]
Hi, apologies if this is a newbie question. I'm running a fairly large druid cluster off an old version of druid-operator, installed before the switch to this repository. Is there a graceful upgrade process where I just enter a command or two and switch from the old Helm charts to the ones in this repo? 

The chart I'm currently running is apparently `druid-operator-0.1.4`

**Comment by AdheipSingh** [comment]
Hi @winsmith 
The CR resources specs are backward compatible, though there might be a few minor tweaks. 
Ill suggest to try this

```
- Scale down existing druid operator to 0.
- Deploy new operator ( check the scope of the operator ). 
- Check for logs, if you see any error in spec reconciliation, fix in the spec. 
```

**Comment by winsmith** [comment]
thanks a lot! I'll make backups and a few dry runs first.
