### ISSUE TITLE
Document Running Druid Without MM on K8s

### ISSUE THREAD

**Issue by AdheipSingh** [datainfrahq/druid-operator#14]
- @churromorales if you can help in here. :)

**Comment by manigarg31** [comment]
Any update here?

**Comment by Zuckster** [comment]
Any updates here?

**Comment by Zuckster** [comment]
Any updates here? [2]

**Comment by AdheipSingh** [comment]
@Zuckster @manigarg31 https://github.com/datainfrahq/druid-operator/pull/120
