### ISSUE TITLE
add annotations on STS

### ISSUE THREAD

**Issue by jb-graindorge-sc** [datainfrahq/druid-operator#142]
Currently [facing an issue with Druid](https://github.com/apache/druid/issues/15956) not able to reload process when TLS certificates are updated, we would like to use https://github.com/stakater/Reloader but it looks like it's not possible to add annotation on Druid sts (we had to do it manually with kubectl) it would be great to be able to annotate sts like we can annotate pods with `podAnnotations`

**Comment by SamWheating** [comment]
This is a good idea - I've been meaning to get more familiar with this CRD so I'll see if I can get this implemented.

**Comment by AdheipSingh** [comment]
noted. We can add this for sure. 
@SamWheating happy to help here. Feel free to reach out over slack for faster iteration.
