### ISSUE TITLE
Release v1.2.4

### ISSUE THREAD

**Issue by TessaIO** [datainfrahq/druid-operator#173]
It would be amazing if we have a new release for v1.2.4. Let me know If I can help with something.

Thanks

**Comment by AdheipSingh** [comment]
@TessaIO can you help in cherry-picking the commits to branch 1.2.3-releases. I'll cut a release from that branch to 1.2.4.

**Comment by TessaIO** [comment]
Sure

**Comment by TessaIO** [comment]
@AdheipSingh any other thing I can help with?

**Comment by TessaIO** [comment]
kind reminder @AdheipSingh
