### ISSUE TITLE
Calling for Collaborators for maintaing the Repo

### ISSUE THREAD

**Issue by AdheipSingh** [datainfrahq/druid-operator#179]
I have been recently super busy and haven't got enough time to maintain the repo. I have been maintaining the code base since 2019 and I would like to call in for collaborators to help maintain the core codebase. 

Collaborators are expected to be current users of the druid operator and be familiar with code base. I will still be involved in reviewing and will be open to have 1:1 calls to discuss PR's. 

I am open to suggestions/recommendations on how to go about this. Feel free to reply here, or get directly in touch with me on [linedkin](https://www.linkedin.com/in/adheipsingh/).

**Comment by TessaIO** [comment]
Btw I'm added to the list of collaborators by @AdheipSingh
