### ISSUE TITLE
Question: Kubebuilder structure

### ISSUE THREAD

**Issue by itamar-marom** [datainfrahq/druid-operator#24]
Why did you choose to move from Kubebuilder's default directories structure? As soon as you need to add a new API, you will need to make lots of changes in order to fit the current custom structure. I'm mainly talking about the `deploy` directory, but the Makefile also.

**Comment by itamar-marom** [comment]
The Makefile also doesn't look fit to the current structure. For instance, the `install` and `deploy` commands are still using Kubebuilder's default structure.

**Comment by AdheipSingh** [comment]
@itamar-marom 
Project was initally bootstraped on operator-sdk and then moved to kubebuilder. The directory structured has been bootstrapped only once, since then we haven't changed any directory.
What issue are you having with Makefile, we can improve on those if you see any issue

**Comment by itamar-marom** [comment]
@AdheipSingh Looking at the PROJECT file you're using Kubebuilder v2 which has a different structure. I currently don't have any problems since I only started to look at this project today. It is just not following the Kubebuilder structure. I don't mind doing the refactor myself and even upgrading this project to V3 which is newer.

I asked that in the druid-operator Slack channel, but I would ask you here also: "...Since I have more coming, I wanted to ask you what is your preferred way for you to get questions? Do you prefer us to ask here? or open GitHub issues?"

**Comment by AdheipSingh** [comment]
> I don't mind doing the refactor myself and even upgrading this project to V3 which is newer.

i personally haven't been strict in following kubebuilder dir structure. regardless, the go mod and the libraries are updated frequently with respect to k8s versions.

>  druid-operator Slack channel, but I would ask you here also: "...Since I have more questions coming, I wanted to ask you 

what is your preferred way for you to get questions?
I am active in all the channels. Feel free to open issues. The more the discussion the better.

I will take a note of your issue. Thanks.
