### ISSUE TITLE
Question: Can I install the druid-operator from operatorhub via Helm?

### ISSUE THREAD

**Issue by chn217** [datainfrahq/druid-operator#28]
Hi team,

I have spent some time to look for a way to install druid-operator from operatorhub via Helm. Do we happen to publish the druid-operator helm chart to elsewhere other than github? The reason is that I want to deploy druid-operator from pipeline, and I don't want to clone the git repo every time for the deployment. 

Thanks

**Comment by AdheipSingh** [comment]
@chn217 yes this something we need to add. Ill create a repo so you can add the repo and use in pipeline. 
Thanks for bringing this up.

**Comment by AdheipSingh** [comment]
@chn217 
```
helm repo add datainfra https://charts.datainfra.io/
helm upgrade --install druid-operator datainfrahq/druid-operator
```
