### ISSUE TITLE
Use predicate to filter out CR Specs NOT to be reconciled

### ISSUE THREAD

**Issue by AdheipSingh** [datainfrahq/druid-operator#4]
- Use predicate to filter out CR Specs NOT to be reconciled #7

**Comment by AdheipSingh** [comment]
Yes, you have got it right.

By main concern what i dont want to handle NOT reconciled or ignored objects within the reconcile loop, they should be part of predicates and getting filtered out before entering the workerqueue. 
I agree on the annotation suggestion

**Comment by itamar-marom** [comment]
Opened a draft PR. I'll work on and test it.
