### ISSUE TITLE
Testing migration to Kubebuilder native framework

### ISSUE THREAD

**Issue by itamar-marom** [datainfrahq/druid-operator#42]
As part of the migration from operatorSDK to Kubebuilder, we also need to refactor the tests into Kuebuilder's framework and structure in order to be aligned with the project.
That means generating the suite_test.go from kubebuilder and adding our currents tests using the gomega and ginkgo frameworks

**Comment by AdheipSingh** [comment]
cc @avtarOPS might be working on this

**Comment by AdheipSingh** [comment]
Thanks @avtarOPS and @gurjotkaur20 for the PR's. Closing this.
