### ISSUE TITLE
K8s v1.26 is not supported 

### ISSUE THREAD

**Issue by vishalgarg837** [datainfrahq/druid-operator#48]
We have upgraded our K8s cluster to v1.26. We had set up the druid operator v1.0.0 on K8s v1.25 for testing and it was working fine even on v1.26 but now when we tried to setup again it's failing because of hpa API version.

Druid-operator / K8s compatibility matrix shows druid operator v1.0.0 works above K8s v1.25, It seems to be ambiguous.
<img width="410" alt="Screenshot 2023-05-02 at 5 52 58 PM" src="https://user-images.githubusercontent.com/20024212/235664967-538805cf-f986-4c7a-a73c-ba965fc37b18.png">

How can we run Druid on K8s v1.26? We are completely blocked now.

Any help would really be appreciated, Thanks in advance.

**Comment by AdheipSingh** [comment]
@vishalgarg837 fixed the doc. 
Thanks for bring
