### ISSUE TITLE
Using additionalContainer not able to add extension libraries

### ISSUE THREAD

**Issue by Plaban67** [datainfrahq/druid-operator#58]
To configure mysql as a metadata storage I need to add mysql-connector-java library to druid extensions, but I am not able to figure out the best way to do so. Tried using additonalContainer as below but its failing to start the container.

  additionalContainer:
    - containerName: download-mysql-connector
      image: apache/druid:25.0.0
      command: ["sh", "-c", "wget -O /tmp/mysql-connector-j-8.0.32.tar.gz https://downloads.mysql.com/archives/get/p/3/file/mysql-connector-j-8.0.32.tar.gz && cd /tmp && tar -xf /tmp/mysql-connector-j-8.0.32.tar.gz && cp /tmp/mysql-connector-j-8.0.32/mysql-connector-j-8.0.32.jar /opt/druid/extensions/mysql-metadata-storage/mysql-connector-java.jar"]
      volumeMounts:
        - name: mysql-connector-jar
          mountPath: /opt/druid/extensions/mysql-connector

If there is a way we can only add initiContainer by nodes, that way we don't have to add libraries to all containers, but only to specific services.

**Comment by AdheipSingh** [comment]
please provide logs from the operator.

**Comment by Plaban67** [comment]
I don't see any error logs from druid-operator related to additonalContainer, but I am also thinking if this the right way to add dependencies to the POD.

**Comment by AdheipSingh** [comment]
@Plaban67 not exactly the right way, init containers are IMO the right way.

Can you send in your druid CR. It would be helpful to debug

**Comment by Plaban67** [comment]
I am using the one from this repository, under charts/crd/templates druid.apache.org_druids.yaml

**Comment by AdheipSingh** [comment]
That is the CRD defination, do you mind sending the CR manifest.

**Comment by Plaban67** [comment]
[druid_cluster.txt](https://github.com/datainfrahq/druid-operator/files/11452977/druid_cluster.txt)

**Comment by Plaban67** [comment]
If we can have initContainer under nodes that way we will have flexibility per node type and doesn't have to execute initial steps across the cluster services.

**For example:**

nodes:
    coordinators:
        kind: Deployment
        nodetype: "coordinator"
        druid.port: 8081 
        image: apache/druid.25.0.0
        env:
        initContainers:
            - name: init-coordinator
               image: apache/druid.25.0.0
               command: ["sh", "-c", "wget -O /tmp/mysql-connector-j-8.0.32.tar.gz https://downloads.mysql.com/archives/get/p/3/file/mysql-connector-j-8.0.32.tar.gz && cd /tmp && tar -xf /tmp/mysql-connector-j-8.0.32.tar.gz && cp /tmp/mysql-connector-j-8.0.32/mysql-connector-j-8.0.32.jar /opt/druid/extensions/mysql-metadata-storage/mysql-connector-java.jar"]

**Comment by Plaban67** [comment]
I was trying to use a wrapper script as a startScript, but unable to start the service. 

spec:
  image: apache/druid:25.0.0
  startScript: /opt/druid/init/initscript.sh


Below initscript.sh

```
#!/bin/bash
# This is a wrapper script that will perform any initial tasks before startup of Druid service

SERVICE=$1

#Download & Place MySQL connector
wget -O /tmp/mysql-connector-j-8.0.32.tar.gz https://downloads.mysql.com/archives/get/p/3/file/mysql-connector-j-8.0.32.tar.gz
cd /tmp
tar -xf /tmp/mysql-connector-j-8.0.32.tar.gz
mv /tmp/mysql-connector-j-8.0.32/mysql-connector-j-8.0.32.jar /opt/druid/extensions/mysql-metadata-storage/mysql-connector-java.jar

#Execute Druid StartUp
sh /druid.sh ${SERVICE}
```

Do you think this is something that can work.

**Comment by AdheipSingh** [comment]
@Plaban67 you can hack the way using script. But the ideal way is to use initContainers. I am adding support for this, will send a PR shortly, will be much appreciated if you can help in testing that out.

**Comment by AdheipSingh** [comment]
@Plaban67 added support for init container here #62
