### ISSUE TITLE
helm: Keep CRD by default so druid clusters are not automatically removed

### ISSUE THREAD

**Issue by AdheipSingh** [datainfrahq/druid-operator#6]
- In reference with PR https://github.com/druid-io/druid-operator/pull/331
- cc @jwitko

**Comment by jwitko** [comment]
@AdheipSingh I'm having trouble submitting a PR against this repo...  
I can submit against any other druid-operator repo out there (the 'original' as well as your personal one or others) but not yours.  Does this repo need some settings changed to allow for a forked-repo PR ?

**Comment by AdheipSingh** [comment]
Let me check now

**Comment by jwitko** [comment]
I think it was on my end because I just changed the upstream and didn't re-fork this repo.  once I forked this repo I see it as an option.

**Comment by AdheipSingh** [comment]
got it. 
thanks
