### ISSUE TITLE
Not able to see PVC in CR Status

### ISSUE THREAD

**Issue by gurjotkaur20** [datainfrahq/druid-operator#65]
Not able to see PVC in CR Status.
Here is the list of PVC:
```
$ kubectl get pvc
NAME                                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-volume-druid-tiny-cluster-historicals-0   Bound    pvc-eab29f7e-73ec-4b92-ac7a-6f2add38647f   2Gi        RWO            standard       10m
data-volume-druid-tiny-cluster-historicals-1   Bound    pvc-8cd53678-49e1-4eca-a2e6-b62a954ffc40   2Gi        RWO            standard       10m
```

CR status:
```
status:
  configMaps:
  - druid-tiny-cluster-brokers-config
  - druid-tiny-cluster-coordinators-config
  - druid-tiny-cluster-historicals-config
  - druid-tiny-cluster-routers-config
  - tiny-cluster-druid-common-config
  deployments:
  - druid-tiny-cluster-brokers
  druidNodeStatus:
    druidNode: All
    druidNodeConditionStatus: "True"
    druidNodeConditionType: DruidClusterReady
    reason: All Druid Nodes are in Ready Condition
  hpAutoscalers:
  - druid-tiny-cluster-brokers
  ingress:
  - druid-tiny-cluster-routers
  podDisruptionBudgets:
  - druid-tiny-cluster-brokers
  pods:
  - druid-tiny-cluster-brokers-f58678f48-snvbd
  - druid-tiny-cluster-coordinators-0
  - druid-tiny-cluster-historicals-0
  - druid-tiny-cluster-historicals-1
  - druid-tiny-cluster-routers-0
  services:
  - druid-tiny-cluster-brokers
  - druid-tiny-cluster-coordinators
  - druid-tiny-cluster-historicals
  - druid-tiny-cluster-routers
  statefulSets:
  - druid-tiny-cluster-coordinators
  - druid-tiny-cluster-historicals
  - druid-tiny-cluster-routers
```

**Comment by AdheipSingh** [comment]
yeah we had that earlier, but removed it since it was hard to maintain. 
To understand more check the func [here](https://github.com/datainfrahq/druid-operator/blob/master/controllers/druid/handler.go#L611).

This is responsible for deleting unused resources, there is a race condition when you delete pod the underlying pvc gets deleted as this func sees it is an orphaned resource. 
This func might need to be improved with additional checks for pvc

**Comment by gurjotkaur20** [comment]
> yeah we had that earlier, but removed it since it was hard to maintain. To understand more check the func [here](https://github.com/datainfrahq/druid-operator/blob/master/controllers/druid/handler.go#L611).
> 
> This is responsible for deleting unused resources, there is a race condition when you delete pod the underlying pvc gets deleted as this func sees it is an orphaned resource. This func might need to be improved with additional checks for pvc

Thanks for the explanation!

**Comment by itamar-marom** [comment]
@gurjotkaur20 can we close this one?
