### ISSUE TITLE
No amd64 docker image for 1.1.1

### ISSUE THREAD

**Issue by johnjeffers** [datainfrahq/druid-operator#66]
When attempting to upgrade from 1.1.0 to 1.1.1.

```
I0518 19:10:59.514979 1 main.go:218] Valid token audiences:
I0518 19:10:59.515043 1 main.go:344] Generating self signed cert as no cert is provided
I0518 19:11:00.480061 1 main.go:394] Starting TCP socket on 0.0.0.0:8443
I0518 19:11:00.480301 1 main.go:401] Listening securely on 0.0.0.0:8443
exec /manager: exec format error
```

I just checked Docker Hub and it looks like the image was only built for arm64. There is no amd64 image.

**Comment by AdheipSingh** [comment]
@johnjeffers pushed for amd64 ( same tag ) and latest tag.

**Comment by johnjeffers** [comment]
Thanks! Confirmed it's working now.

**Comment by AdheipSingh** [comment]
@johnjeffers cool. BTW we have a [druid slack channel](https://kubernetes.slack.com/?redir=%2Farchives%2FC04F4M6HT2L) for faster iteration you can reach out. Join #druid-operator channel :)
