### ISSUE TITLE
support Pod topology spread constraints

### ISSUE THREAD

**Issue by itamar-marom** [datainfrahq/druid-operator#71]
Support Kubernetes Pod topology spread constraints.

- https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#pod-topology-spread-constraints

**Comment by bkalcho** [comment]
I see this setting has been exposed in `DruidNodeSpec`:
https://github.com/datainfrahq/druid-operator/blob/master/docs/api_specifications/druid.md#druidnodespec

There is exposed `topologySpreadConstraints`. Is this working or not?

**Comment by AdheipSingh** [comment]
it is working @bkalcho
