### ISSUE TITLE
Operator does not seem to respect the recommended upgrade order

### ISSUE THREAD

**Issue by johnjeffers** [datainfrahq/druid-operator#81]
When performing upgrades, the Operator appears to restart all of the deployments/daemonsets at the same time, rather than respecting the recommended order as defined here: https://druid.apache.org/docs/latest/operations/rolling-updates.html

Is there any way to change this behavior?

**Comment by itamar-marom** [comment]
Hi @johnjeffers, can you please send provide some more information here?
- Your `Druid` object
- What did you change
- What happened
- What did you expect it to do (and why)

**Comment by johnjeffers** [comment]
What I changed was the Druid version number. I upgraded from Druid 25.0.0 to 26.0.0.

I didn't have any expections about what would happen, I just noticed that when it upgraded all the components, it seems to do them all at once instead of the rolling order that is recommended.

**Comment by AdheipSingh** [comment]
@johnjeffers please enable ```rollingDeploy: true``` in your configs.

**Comment by johnjeffers** [comment]
Thanks! I just enabled it. We'll see how it goes at the next upgrade. This seems like a pretty important setting, and I overlooked it. Is there any way this could have some attention drawn to it by including it in the examples?

**Comment by AdheipSingh** [comment]
@johnjeffers yes, IMHO i feel this should be the default setting. You don't want to do parallel upgrades a database :)

**Comment by itamar-marom** [comment]
@AdheipSingh I agree, opened a change for it. This is a breaking change tho.
