### ISSUE TITLE
Supports deploying sidecars to individual druid service's pod rather than to all pods

### ISSUE THREAD

**Issue by devy1540** [datainfrahq/druid-operator#84]
I need to deploy a sidecar container on my broker, but the operator seems to configure it to only deploy to all pods.

I would like to see support for deploying sidecars to individual pods.

**Comment by itamar-marom** [comment]
Hi @devy1540 can you describe your use-case?

**Comment by devy1540** [comment]
@itamar-marom 

of course!
When druid's request logging function is activated as a file, logs are left in the broker, and we try to collect the logs with fluentbit.
There is no need to use fluentbit for other services (ex. historical, router..), but if you use the additional container function, containers are installed in all services.

**Comment by itamar-marom** [comment]
Sounds valid to me. @AdheipSingh - your opinion?

**Comment by itamar-marom** [comment]
@devy1540 FYI, it will be ready soon.

**Comment by devy1540** [comment]
@itamar-marom thanks for the good news
