### ISSUE TITLE
publish v1.0.0 to charts index

### ISSUE THREAD

**Issue by vamsi-globality** [datainfrahq/druid-operator#88]
Kubernetes clusters running version <=1.25 will need app version 1.0.0 (charts v0.2.0) available on public helm repo index.
https://charts.datainfra.io/index.yaml

Currently, only v1.1.1 and v1.1.0 are available for helm pull.

**Comment by itamar-marom** [comment]
Hi @vamsi-globality, I'm cleaning old issues. As I remember, we solved this one right?
If not, is it still needed?
I'm closing it, feel free to reopen it if needed.
