### ISSUE TITLE
HostNetwork to the historical nodes

### ISSUE THREAD

**Issue by freemanlutsk** [datainfrahq/druid-operator#90]
Dear community,

Is there any to add `HostNetwork: true` to the pod specs for historical service?

Thank You!

**Comment by itamar-marom** [comment]
Hi @freemanlutsk 
It is currently no supported and generally not secure. What is your use-case?

**Comment by freemanlutsk** [comment]
Hi @itamar-marom 

>What is your use-case?

I would like to utilize the storage/CPU resources in my k8s cluster by adding to my existing Druid cluster (not in the k8s) an additional `historical` tier.
As a workaround, I use `kubectl patch sts ...`, but would be good to have the ability in the Helm Chart

Regards,
Yurii

**Comment by AdheipSingh** [comment]
@freemanlutsk @itamar-marom 
Does setting host network to true have any security issues ?

**Comment by itamar-marom** [comment]
from OWASP project: https://cheatsheetseries.owasp.org/cheatsheets/Kubernetes_Security_Cheat_Sheet.html#assess-the-privileges-used-by-containers

**Comment by freemanlutsk** [comment]
Maybe there is another way to expose `historical` nodes for the external `brokers`?

**Comment by AdheipSingh** [comment]
@freemanlutsk kubernetes service to expose historicals ? ```LoadBalancer``` or an ingress route

**Comment by AdheipSingh** [comment]
feel free to open, providing sufficient usecases. 
Thanks
