### ISSUE TITLE
Support TLS Certificates

### ISSUE THREAD

**Issue by spstarr** [datainfrahq/druid-operator#93]
While looking at the `Druid` CRD, I don't see any information on how we can pass a CA certificate to the operator.

Either via a K8s Secret or $CLOUD provider method to get the secret passed in.

I was thinking of using an ExternalSecret --> $CLOUD provider secret manager and then referencing the Secret via the Operator but no such luck.

Is this correct?

Thanks,
Shawn

**Comment by itamar-marom** [comment]
Hi @spstarr 
Isn't mounting a secret as a volume enough?

**Comment by spstarr** [comment]
druid.metadata.postgres.ssl.sslMode=verify-ca
#druid.metadata.postgres.ssl.sslCert=/psqlcertificates/server.crt
#druid.metadata.postgres.ssl.sslKey=/psqlcertificates/server.key
druid.metadata.postgres.ssl.sslRootCert=/psqlcertificates/ca.crt

Ok, yes volume mount will do... I forgot about that part =)

**Comment by itamar-marom** [comment]
@spstarr if you have a working example it would be great to add it to the docs here :)
